# Valentina's script 
# Dataset: ESS Round 2

rm(list = ls())

#packages we need for data management 
library(foreign)
library(dplyr)

# 1. Importing ROUND 2  datset 
ESS02 <- read.dta("D:/R Projects/ESS Datasets/ESS2/ESS2e03_6.dta")

View(ESS02$iscoco)
# 2. Selecting needed variables
ESS02<- select(ESS02, essround, cntry, freehms, gndr, rlgdgr,
              rlgatnd, pray, rlgblg, rlgdnm, agea, marital, edulvla, hinctnt,
                  domicil, impenv, chldhhe,imwbcnt, imueclt, iscoco, mnrgtjb,dweight,
              pspwght, pweight)

class(ESS02$cntry)
#cntry var: transformed as factor (categorical)
ESS02$cntry<- as.factor(ESS02$cntry)
summary(ESS02$cntry)

# 3. selecting countries needed
ESS02 <- filter(
  ESS02,
  cntry %in% c("AT", "BE", "CH", "CZ", "DE", "EE", "FI", "FR", "GB", "HU", "IE", "IT", "NO", "PL", "NL", "SI")
)

summary(ESS02$cntry)


# 4. recoding variable age in six categories 
ESS02$AGE6cat <- ifelse(ESS02$agea < 25,
                          "14-24",
                          ifelse(ESS02$agea < 35,
                                 "25-34",
                                 ifelse(ESS02$agea < 45,
                                        "35-44",
                                        ifelse(ESS02$agea < 55,
                                               "45-54",
                                               ifelse(ESS02$agea < 65,
                                                      "55-64",
                                                      ifelse(ESS02$agea < 75,
                                                             "65-74",
                                                             "75+"))))
                                 
                          )
)

ESS02$AGE6cat <- factor(ESS02$AGE6cat, ordered = TRUE)

summary(ESS02$AGE6cat)

# 5. recode level of education
summary(ESS02$edulvla)

ESS02 <- mutate(
  ESS02,
  EDUCATION = recode(edulvla,
                     "Less than lower secondary education (ISCED 0-1)" = "Low level",
                     "Lower secondary education completed (ISCED 2)" = "Low level",
                     "Upper secondary education completed (ISCED 3)" = "Medium level",
                     "Post-secondary non-tertiary education completed (ISCED 4)" = "Medium level",
                     "Tertiary education completed (ISCED 5-6)" = "High level"))

summary(ESS02$EDUCATION)
ESS02$EDUCATION <- factor(ESS02$EDUCATION, ordered = TRUE)


# 6. Recoding occupation 
summary(ESS02$iscoco)

#for occupation in the cumulative ESS we have iscoco for rounds 1-5 and isco08 for rounds 6-7
ESS02 <- mutate(
  ESS02,
  OCCUPATION = recode(iscoco,
                      "Managing directors and chief executives" = "Managers",
                      "Manufacturing managers" = "Managers",
                      "Retail and wholesale trade managers" = "Managers",
                      "Sales and marketing managers" = "Managers",
                      "Supply, distribution and related managers" = "Managers",
                      "Restaurant managers" = "Managers",
                      "Managers in manufacturing"= "Managers",
                      "Managers not elsewhere classified" = "Managers",
                      "Construction managers" = "Managers",
                      "Managers in wholesale and retail trade" = "Managers",
                      "Managers of small enterprises" = "Managers",
                      "Education managers" = "Managers",
                      "Finance and administration  managers" = "Managers",
                      "Professional services managers not elsewhere classified" = "Managers",
                      "Mngr small ent wholesale and retail trade" = "Managers",
                      "Services managers not elsewhere classified" = "Managers",
                      "Production and operations managers" = "Managers",
                      "Directors and chief executives" = "Managers",
                      "Oth spec managers not elsewhere classified" = "Managers",
                      "Mngr small ent not elsewhere classified"= "Managers",
                      "Managers of small enterprises"= "Managers",
                      "Mngr small ent transp,storage,comm"= "Managers",
                      "Mngr small ent pers care,cleaning,rel serv"= "Managers",
                      "Mngr small ent of restaurants and hotels"= "Managers",
                      "Managers in construction"= "Managers",
                      "Mngr small ent in construction"= "Managers",
                      "Managers in restaurants and hotels"= "Managers",
                     "Research and development managers" = "Managers",
                     "Mngr small ent agr,hunting,forestry,fishing" = "Managers",
                     "Mngr small ent in manufacturing" = "Managers",
                     "Mngr small ent of business serv enterpr" = "Managers",
                     "Personnel and industrial relations managers" = "Managers",
                     "Managers in business services enterprises" = "Managers",
                     "Managers transport,storage,communications"  = "Managers",
                     "Supply and distribution  managers" = "Managers",
                     "Managers agriculture,hunting,forestry,fishing" = "Managers",
                     "Managers personal care,cleaning,rel serv" = "Managers",
                     "Legislators, senior officials and managers" = "Managers",
                     "Computing services managers"= "Managers",
                     "Legislators, senior government officials" = "Managers", 
                     "Other specialist managers"= "Managers", 
                     "Advertising and public relations managers" = "Managers", 
                     "Senior off human, special-interest org" = "Managers",
                     "Senior officials of special-interest org"= "Managers",
                     "Senior officials of economic-interest org"= "Managers",
                     "Legislators and senior officials" = "Managers", 
                     "Corporate managers" = "Managers", 
                     "Senior officials of political-party org"= "Managers",
                      
                    
                      "Secondary education teachers" = "Professionals",
                      "Nursing associate professionals" = "Professionals",
                      "Primary school teachers" = "Professionals",
                      "Nursing professionals" = "Professionals",
                      "Accountants" = "Professionals",
                     "Hygienists, health environmental officers"= "Professionals",
                      "Social work and counselling professionals" = "Professionals",
                      "Early childhood educators" = "Professionals",
                      "Teaching professionals" = "Professionals",
                      "Teaching professionals not elsewhere classified" = "Professionals",
                      "University and higher education teachers" = "Professionals",
                      "Primary education teaching professionals" = "Professionals",
                      "Management and organization analysts" = "Professionals",
                      "Software developers" = "Professionals",
                      "Policy administration professionals" = "Professionals",
                      "Vocational education teachers" = "Professionals",
                      "Technical and medical sales professionals (excluding ICT)" = "Professionals",
                      "Civil engineers" = "Professionals",
                      "Lawyers" = "Professionals",
                      "Advertising and marketing professionals" = "Professionals",
                      "Engineering professionals not elsewhere classified" = "Professionals",
                      "Mechanical engineers" = "Professionals",
                      "Financial and investment advisers" = "Professionals",
                      "Secondary education teaching professionals" = "Professionals",
                      "Business prof not elsewhere classified" = "Professionals",
                      "Medical doctors" = "Professionals",
                      "Comp systems designers,analysts,programmers" = "Professionals",
                      "Primary education teaching associate prof"  = "Professionals",
                      "Coll,univ, higher educ teaching prof"   = "Professionals",
                      "Pre-primary edu teaching associate prof" = "Professionals",
                      "Other teaching associate professionals"  = "Professionals",
                      "Arch, engin,rel prof not elsewhere class"   = "Professionals",
                      "Other teaching prof not elsewhere class"   = "Professionals",
                      "Pre-primary educ teaching professionals"  = "Professionals",
                      "Authors, journalists and other writers" = "Professionals",
                      "Social work professionals" = "Professionals",
                      "Architects, town and traffic planners"= "Professionals",
                      "Health ass prof excpt nursing not else class" = "Professionals",
                     "Pharmacists"  = "Professionals",
                     "Primary and pre-primary educ teaching prof"  = "Professionals",
                     "Health prof (not nursing) not elsew class" = "Professionals",
                     "Psychologists" = "Professionals",
                     "Composers, musicians and singers" = "Professionals",
                     "Dentists" = "Professionals",
                     "Electronics, telecommunications engineers" = "Professionals",
                     "Education methods specialists" = "Professionals",
                     "Electrical engineers" = "Professionals",
                     "Religious professionals" = "Professionals",
                     "Film, stage and related actors and directors"= "Professionals",
                     "Sculptors, painters and related artists" = "Professionals",
                     "Judges" = "Professionals",
                     "Social science and related professionals" = "Professionals",
                     "Veterinarians" = "Professionals",
                     "Archivists and curators" = "Professionals",
                     "Cartographers and surveyors" = "Professionals",
                     "Chemists" = "Professionals",
                     "Chemical engineers" = "Professionals",
                     "Writers and creative or performing artists" = "Professionals",
                     "Biol,botan,zool and related professionals" = "Professionals",
                     "Health professionals (except nursing)" = "Professionals",
                     "Philologists, translators and interpreters"= "Professionals",
                     "Mining engineers, metall,rel professionals"= "Professionals",
                     "Other teaching professionals"= "Professionals",
                     "Computing professionals"= "Professionals",
                     "Personnel and careers professionals"= "Professionals",
                     "Architects,engineers,related professionals" = "Professionals",
                     "Special education teaching professionals" = "Professionals",
                     "Economists"= "Professionals",
                     "Dieticians and nutritionists" = "Professionals",
                     "Public service administrative professionals" = "Professionals",
                     "Librarians,related information prof" = "Professionals",
                     "Archiv,libr,related information prof" = "Professionals",
                     "Ships' engineers"= "Professionals",
                     "Comp professionals not elsewhere classified" = "Professionals",
                     "Legal prof not elsewhere classified"  = "Professionals",
                     "Legal professionals"   = "Professionals",
                     "Business professionals"  = "Professionals",
                     "Other professionals" = "Professionals",
                     "Radio, television and other announcers" = "Professionals",
                     "Farming and forestry advisers" = "Professionals",
                     "Sociologists, anthropologists, rel prof" = "Professionals",
                     "Statisticians" = "Professionals",
                     "School inspectors" = "Professionals",
                     "Optometrists and opticians"= "Professionals",
                     "Philosophers,historians,political scientists" = "Professionals",
                     "Street,nightclub,rel musicians,singers,dance"= "Professionals",
                     "Life science professionals" = "Professionals",
                     "Mathematicians and related professionals" = "Professionals",
                     "Choreographers and dancers" = "Professionals",
                     "Meteorologists" = "Professionals",
                     "Phys, mathem, engin science professionals" = "Professionals",
                     "Mathem, stat, related professionals" = "Professionals",
                     "Geologists and geophysicists"= "Professionals",
                     "Pharm, pathol and related professionals"= "Professionals",
                     "Physicists and astronomers"= "Professionals",
                     "Life science and health professionals" = "Professionals",
                     "Agronomists and related professionals"= "Professionals",
                     "Physics, chemists, related professionals"= "Professionals",
                      
                      "Accounting associate professionals" = "Technicians and Associate Professionals",
                      "Draughtspersons" = "Technicians and Associate Professionals",
                      "Social work associate professionals" = "Technicians and Associate Professionals",
                      "Administrative and executive secretaries" = "Technicians and Associate Professionals",
                      "Commercial sales representatives" = "Technicians and Associate Professionals",
                      "Bookkeepers" = "Technicians and Associate Professionals",
                      "Manufacturing supervisors" = "Technicians and Associate Professionals",
                      "Office supervisors" = "Technicians and Associate Professionals",
                      "Insurance representatives" = "Technicians and Associate Professionals",
                      "Buyers" = "Technicians and Associate Professionals",
                      "Adm secretaries, related associate prof" = "Technicians and Associate Professionals",
                      "Technical and commercial sales rep" = "Technicians and Associate Professionals",
                      "Physical and engineering science technicians not elsewhere classified" = "Technicians and Associate Professionals",
                      "Nursing and midwifery professionals" = "Technicians and Associate Professionals",
                      "Administrative associate professionals" = "Technicians and Associate Professionals",
                      "Finance,sales associate prof not else class" = "Technicians and Associate Professionals",
                      "Phys, engin science techn not elsew class" = "Technicians and Associate Professionals",
                      "Safety, health and quality inspectors" = "Technicians and Associate Professionals",
                      "Mechanical engineering technicians" = "Technicians and Associate Professionals",
                      "Civil engineering technicians"= "Technicians and Associate Professionals",
                     "Estate agents" = "Technicians and Associate Professionals",
                     "Safety and quality inspectors" = "Technicians and Associate Professionals",
                     "Government tax and excise officials"  = "Technicians and Associate Professionals",
                     "Medical assistants"  = "Technicians and Associate Professionals",
                      "Physiotherapists and rel associate prof" = "Technicians and Associate Professionals",
                      "Finance and sales associate professionals" = "Technicians and Associate Professionals",
                      "Police inspectors and detectives" = "Technicians and Associate Professionals",
                     "Legal related business associate prof"  = "Technicians and Associate Professionals",
                     "Custom,tax,related gov associate prof"  = "Technicians and Associate Professionals",
                     "Special education teaching associate prof"  = "Technicians and Associate Professionals",
                     "Life science technicians"  = "Technicians and Associate Professionals",
                     "Decorators and commercial designers" = "Technicians and Associate Professionals",
                     "Computer assistants"= "Technicians and Associate Professionals",
                     "Electrical engineering technicians" = "Technicians and Associate Professionals",
                     "Busines,serv,agnts,trde brokr not else class" = "Technicians and Associate Professionals",
                     "Ships' deck officers and pilots"= "Technicians and Associate Professionals",
                     "Mining and metallurgical technicians" = "Technicians and Associate Professionals",
                     "Midwifery associate professionals" = "Technicians and Associate Professionals",
                     "Artistic,entertainment,sports associate prof" = "Technicians and Associate Professionals",
                     "Air traffic controllers" = "Technicians and Associate Professionals",
                     "Customs and border inspectors" = "Technicians and Associate Professionals",
                     "Veterinary assistants" = "Technicians and Associate Professionals",
                     "Other associate professionals" = "Technicians and Associate Professionals",
                     "Incinerator,watertreatment,rel plant operator"= "Technicians and Associate Professionals",
                     "Electronics,telecom engineering technicians" = "Technicians and Associate Professionals",
                     "Broadcasting,telecom equipment operators"= "Technicians and Associate Professionals",
                      "Building and fire inspectors" = "Technicians and Associate Professionals",
                     "Trade brokers" = "Technicians and Associate Professionals",
                     "Ship, aircraft controllers and technicians" = "Technicians and Associate Professionals",
                     "Chemical engineering technicians"= "Technicians and Associate Professionals",
                     "Chemical and physical science technicians"= "Technicians and Associate Professionals",
                     "Athletes,sportspers, related associate prof"= "Technicians and Associate Professionals",
                     "Religious associate professionals"= "Technicians and Associate Professionals",
                     "Physical,engineering science technicians" = "Technicians and Associate Professionals",
                     "Agronomy and forestry technicians" = "Technicians and Associate Professionals",
                     "Statistical, mathemat rel associate prof" = "Technicians and Associate Professionals",
                     "Computer associate professionals" = "Technicians and Associate Professionals",
                     "Nursing midwifery associate prof" = "Technicians and Associate Professionals",
                     "Health associate prof (except nursing)" = "Technicians and Associate Professionals",
                     "Computer equipment operators" = "Technicians and Associate Professionals",
                     "Securities and finance dealers and brokers" = "Technicians and Associate Professionals",
                     "Clearing and forwarding agents" = "Technicians and Associate Professionals",
                     "Dental assistants" = "Technicians and Associate Professionals",
                     "Industrial robot controllers"= "Technicians and Associate Professionals",
                     "Clowns,magicians,acrobats, rel associate prof"= "Technicians and Associate Professionals",
                     "Teaching associate professionals" = "Technicians and Associate Professionals",
                     "Business services agents and trade brokers" = "Technicians and Associate Professionals",
                     "Government licensing officials" = "Technicians and Associate Professionals",
                     "Life,science techn and rel associate prof"= "Technicians and Associate Professionals",
                     "Appraisers, valuers and auctioneers" = "Technicians and Associate Professionals",
                     "Government social benefits officials" = "Technicians and Associate Professionals",
                     "Air traffic safety technicians" = "Technicians and Associate Professionals",
                     "Technicians and associate professionals"= "Technicians and Associate Professionals",
                     "Physical,engineering science associate prof" = "Technicians and Associate Professionals",
                     "Pharmaceutical assistants" = "Technicians and Associate Professionals",
                     "Photogr,image,sound rec equipment oper" = "Technicians and Associate Professionals",
                     "Aircraft pilots, related associated prof"= "Technicians and Associate Professionals",
                     "Life,science and health associate prof" = "Technicians and Associate Professionals",
                     "Custom,tax,rel gov assoc prof not else class"= "Technicians and Associate Professionals",
                     "Optical,electr equipm oper not elsew class" = "Technicians and Associate Professionals",
                     "Medical equipment operators" = "Technicians and Associate Professionals",
                     
                     
                      "General office clerks " = "Clerical Support Workers",
                      "Accounting and bookkeeping clerks" = "Clerical Support Workers",
                      "Tellers and other counter clerk" = "Clerical Support Workers",
                      "Office clerks" = "Clerical Support Workers",
                      "Statistical and finance clerks"= "Clerical Support Workers",
                      "Secretaries" = "Clerical Support Workers",
                      "Secretaries (general)" = "Clerical Support Workers",
                      "Stock clerks" = "Clerical Support Workers",
                      "Mail carriers and sorting clerks" = "Clerical Support Workers",
                      "Bank tellers and related clerks" = "Clerical Support Workers",
                      "Other office clerks" = "Clerical Support Workers",
                      "Receptionists (general)" = "Clerical Support Workers",
                      "Transport clerks" = "Clerical Support Workers",
                      "Receptionists and information clerks" = "Clerical Support Workers",
                      "Tellers and other counter clerks" = "Clerical Support Workers",
                      "Telephone switchboard operators" = "Clerical Support Workers",
                      "Clerks" = "Clerical Support Workers",
                      "Secretaries and keyboard-operating clerks"= "Clerical Support Workers",
                     "Data entry operators" = "Clerical Support Workers",
                     "Stenographers and typists" = "Clerical Support Workers",
                     "Production clerks" = "Clerical Support Workers",
                     "Customer services clerks" = "Clerical Support Workers",
                     "Library and filing clerks"= "Clerical Support Workers",
                     "Numerical clerks" = "Clerical Support Workers",
                     "Cashiers, tellers and related clerks"= "Clerical Support Workers",
                     "Travel agency and related clerks"= "Clerical Support Workers",
                     "Debt-collectors and related workers"= "Clerical Support Workers",
                     "Library, mail and related clerks"= "Clerical Support Workers",
                     "Client information clerks"= "Clerical Support Workers",
                     "Bookmakers and croupiers"= "Clerical Support Workers",
                     "Calculating-machine operators" = "Clerical Support Workers",
                     "Word-processor and related operators"  = "Clerical Support Workers",
                     "Material-recording and transport clerks"  = "Clerical Support Workers",
                     "Travel consultants and organisers" = "Clerical Support Workers",
                     "Coding, proof-reading and related clerks" = "Clerical Support Workers",
                     "Scribes and related workers"= "Clerical Support Workers",
                     "Pawnbrokers and money-lenders"= "Clerical Support Workers",
                      
                      "Shop sales assistants" = "Services and Sales Workers",
                      "Waiters" = "Services and Sales Workers",
                      "Cooks" = "Services and Sales Workers",
                      "Health care assistants" = "Services and Sales Workers",
                      "Child care workers" = "Services and Sales Workers",
                      "Home-based personal care workers" = "Services and Sales Workers",
                      "Hairdressers" = "Services and Sales Workers",
                      "Cashiers and ticket clerks" = "Services and Sales Workers",
                      "Shop keepers" = "Services and Sales Workers",
                      "Security guards" = "Services and Sales Workers",
                      "Shop supervisors" = "Services and Sales Workers",
                      "Teachers' aides" = "Services and Sales Workers",
                      "Beauticians and related workers" = "Services and Sales Workers",
                      "Police officers" = "Services and Sales Workers",
                      "Waiters, waitresses and bartenders" = "Services and Sales Workers",
                      "Bartenders" = "Services and Sales Workers",
                      "Institution-based personal care workers" = "Services and Sales Workers",
                      "Child-care workers" = "Services and Sales Workers",
                      "Hairdress,barber,beautician, related workers" = "Services and Sales Workers",
                      "Personal care and related workers" = "Services and Sales Workers",
                      "Protective services workers not else class" = "Services and Sales Workers",
                      "Housekeepers and related workers" = "Services and Sales Workers",
                     "Fire-fighters" = "Services and Sales Workers",
                     "Transport conductors" = "Services and Sales Workers",
                     "Personal and protective services workers"= "Services and Sales Workers",
                     "Travel attendants and travel stewards" = "Services and Sales Workers",
                     "Models, salespersons and demonstrators"= "Services and Sales Workers",
                     "Travel guides" = "Services and Sales Workers",
                     "Service workers,shop, market sales workers" = "Services and Sales Workers",
                     "Door-to-door and telephone salespersons"= "Services and Sales Workers",
                     "Housekeeping, restaurant services workers"= "Services and Sales Workers",
                     "Protective services workers"= "Services and Sales Workers",
                     "Personal care,related workers not else class"= "Services and Sales Workers",
                     "Other pers service workers not else class" = "Services and Sales Workers",
                     "Prison guards" = "Services and Sales Workers",
                     "Undertakers and embalmers"= "Services and Sales Workers",
                     "Fashion and other models" = "Services and Sales Workers",
                     "Travel attendants and related workers" = "Services and Sales Workers",
                     "Companions and valets"= "Services and Sales Workers",
                     "Building caretakers,window, rel cleaner"= "Services and Sales Workers",
                     "Other personal services workers"= "Services and Sales Workers",
                      
                      "Mixed crop and animal producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Field crop and vegetable growers"= "Skilled Agricultural, Forestry and Fishery Workers",
                      "Crop and animal producers " = "Skilled Agricultural, Forestry and Fishery Workers",
                       "Livestock and dairy producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Gardeners, horticultural and nursery growers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Dairy and livestock producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Gardeners, horticultural, nursery growers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Forestry and related workers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Crop and animal producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Animal prod, related workers not else class" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Poultry producers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Skilled agricultural and fishery workers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Inland and coastal waters fishery workers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Animal producers and related workers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Market gardeners and crop growers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Deep-sea fishery workers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Aquatic-life cultivation workers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Forestry workers and loggers" = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Charcoal burners and related workers " = "Skilled Agricultural, Forestry and Fishery Workers",
                     "Hunters and trappers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Fishery workers, hunters and trappers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     "Charcoal burners and related workers"= "Skilled Agricultural, Forestry and Fishery Workers",
                     
                      "Motor vehicle mechanics and repairers" = "Craft and Related Trades Workers",
                     "Craft and Related Trades Workers"= "Craft and Related Trades Workers",
                      "Carpenters and joiners" = "Craft and Related Trades Workers",
                      "Bricklayers and related workers" = "Craft and Related Trades Workers",
                      "Building and related electricians" = "Craft and Related Trades Workers",
                      "Metal working machine tool setters and operators" = "Craft and Related Trades Workers",
                      "Agricultural and industrial machinery mechanics and repairers" = "Craft and Related Trades Workers",
                      "Plumbers and pipe fitters" = "Craft and Related Trades Workers",
                      "Tailors, dressmakers, furriers and hatters" = "Craft and Related Trades Workers",
                      "Bakers, pastry-cooks and confectionery makers" = "Craft and Related Trades Workers",
                      "Structural-metal preparers and erectors" = "Craft and Related Trades Workers",
                      "Painters and related workers" = "Craft and Related Trades Workers",
                      "House builders" = "Craft and Related Trades Workers",
                      "Welders and flamecutters" = "Craft and Related Trades Workers",
                      "Electrical mechanics and fitters" = "Craft and Related Trades Workers",
                      "Cabinet-makers and related workers" = "Craft and Related Trades Workers",
                      "Product graders and testers (excluding foods and beverages)" = "Craft and Related Trades Workers",
                      "Bricklayers and stonemasons" = "Craft and Related Trades Workers",
                      "Motor vehicle mechanics and fitters" = "Craft and Related Trades Workers",
                      "Electric mechanic, fitters and servicers" = "Craft and Related Trades Workers",
                      "Tailors, dressmakers and hatters" = "Craft and Related Trades Workers",
                      "Agricultural- or Industrial-machinery Mechanics and Fitters" = "Craft and Related Trades Workers",
                     "Agric- or industrmachine mechanic and fitter" = "Craft and Related Trades Workers",
                      "Sewers, embroiderers and related workers" = "Craft and Related Trades Workers",
                      "Tool-makers and related workers" = "Craft and Related Trades Workers",
                      "Bakers,pastry-cooks,confectionery maker" = "Craft and Related Trades Workers",
                      "Cabinetmakers and related workers"  = "Craft and Related Trades Workers",
                      "Build frame, rel trade worker not else class" = "Craft and Related Trades Workers",
                      "Builders"  = "Craft and Related Trades Workers",
                      "Electronic mecanic, fitters and servicers"   = "Craft and Related Trades Workers",
                      "Butchers,fishmongers,related food preparers" = "Craft and Related Trades Workers",
                      "Building frame and related trades workers"  = "Craft and Related Trades Workers",
                      "Machine-tool setters and setter-operators"  = "Craft and Related Trades Workers",
                      "Sheet-metal workers"  = "Craft and Related Trades Workers",
                     "Weavers, knitters and related workers"  = "Craft and Related Trades Workers",
                     "Compositors,typesetters, related workers"  = "Craft and Related Trades Workers",
                     "Roofers" = "Craft and Related Trades Workers",
                     "Metalm,welder,sheetmet,structmet prep,rel work" = "Craft and Related Trades Workers",
                      "Plasterers" = "Craft and Related Trades Workers",
                     "Craft and related trades workers"= "Craft and Related Trades Workers",
                     "Upholsterers and related workers" = "Craft and Related Trades Workers",
                     "Electric line install,repairer,cable jointer" = "Craft and Related Trades Workers",
                     "Telegraph, teleph installers and servicers" = "Craft and Related Trades Workers",
                     "Textile,leather,rel patternmakers, cutter"= "Craft and Related Trades Workers",
                     "Handicrft work in textile,leather,rel mater" = "Craft and Related Trades Workers",
                     "Handicrft work in wood and related material" = "Craft and Related Trades Workers",
                     "Glass-makers,cutters,grinders and finishers" = "Craft and Related Trades Workers",
                     "Build finishers, related trades workers"= "Craft and Related Trades Workers",
                     "Painter,building struct cleaner,rel trde work" = "Craft and Related Trades Workers",
                     "Bookbinders and related workers" = "Craft and Related Trades Workers",
                     "Craft printing and related trades workers" = "Craft and Related Trades Workers",
                     "Metal moulders and coremakers"= "Craft and Related Trades Workers",
                     "Metal wheelgrinder, polisher, tool"= "Craft and Related Trades Workers",
                     "Floor layers and tile setters"= "Craft and Related Trades Workers",
                     "Insulation workers"= "Craft and Related Trades Workers",
                     "Metal, machinery related trades workers" = "Craft and Related Trades Workers",
                     "Textile,garment, related trades worker"  = "Craft and Related Trades Workers",
                     "Food processing and related trades workers"   = "Craft and Related Trades Workers",
                     "Concrete placer,concrete finisher, rel workrs"   = "Craft and Related Trades Workers",
                     "Jewellery and precious-metal workers"   = "Craft and Related Trades Workers",
                     "Precision-instrument makers and repairers"  = "Craft and Related Trades Workers",
                     "Build finisher,rel trde work not else class" = "Craft and Related Trades Workers",
                     "Wood treaters,cabinet-makers,rel trad work"  = "Craft and Related Trades Workers",
                     "Woodworking machine setter,setter-" = "Craft and Related Trades Workers",
                     "Glaziers" = "Craft and Related Trades Workers",
                     "Fruit, vegetable and related preservers" = "Craft and Related Trades Workers",
                     "Abrasive wheel former,potter and rel workers"  = "Craft and Related Trades Workers",
                     "Shotfirers and blasters"  = "Craft and Related Trades Workers",
                     "Pelt dressers, tanners and fellmongers" = "Craft and Related Trades Workers",
                     "Riggers and cable splicers"  = "Craft and Related Trades Workers",
                     "Fibre preparers" = "Craft and Related Trades Workers",
                     "Miners,shotfirers, stone cutters, carvers" = "Craft and Related Trades Workers",
                     "Stone splitters, cutters and carvers"= "Craft and Related Trades Workers",
                     "Blacksmith, hammer-smith,forging-press work"= "Craft and Related Trades Workers",
                     "Tobacco preparers,tobacco products maker" = "Craft and Related Trades Workers",
                     "Musical instrument makers and tuners"= "Craft and Related Trades Workers",
                     "Building structure cleaners"= "Craft and Related Trades Workers",
                     "Metal wheelgrinder, polisher, tool sharpener"= "Craft and Related Trades Workers",
                     "Basketry weavers,brush makers,rel worker" = "Craft and Related Trades Workers",
                     "Food and beverage tasters and graders" = "Craft and Related Trades Workers",
                     "Stereotypers and electrotypers" = "Craft and Related Trades Workers",
                     "Blacksmiths,tool-makers,related trad work"= "Craft and Related Trades Workers",
                     "Underwater workers"= "Craft and Related Trades Workers",
                     "Furriers and related workers"= "Craft and Related Trades Workers",
                     "Wood treaters"= "Craft and Related Trades Workers",
                     "Precision,handicraft,printing,rel trade work"= "Craft and Related Trades Workers",
                     "Glass,ceramics and rel decorative painters"= "Craft and Related Trades Workers",
                     "Printing engravers and etchers"= "Craft and Related Trades Workers",
                     "Glass engravers and etchers" = "Craft and Related Trades Workers",
                     "Extraction and building trades workers"= "Craft and Related Trades Workers",
                     "Precision workers in metal and rel materials"= "Craft and Related Trades Workers",
                     "Other craft and related trades workers"= "Craft and Related Trades Workers",
                     "Pelt,leather,shoemaking trades worker"= "Craft and Related Trades Workers",
                     "Potters,glass-makers, related trades workers"= "Craft and Related Trades Workers",
                     "Silk-screen,block,craft textile printers"= "Craft and Related Trades Workers",
                     "Electric,electronic equip mech and fitter"= "Craft and Related Trades Workers",
                     "Aircraft engine mechanics and fitters"= "Craft and Related Trades Workers",
                     "Craft and Related Trades Workers"= "Craft and Related Trades Workers",
                     "Handicrft work wood,textile,leather,rel matr"= "Craft and Related Trades Workers",
                     
                      "Heavy truck and lorry drivers" = "Plant and Machine Operators and Assemblers",
                      "Car, taxi and van drivers" = "Plant and Machine Operators and Assemblers",
                      "Mechanical machinery assemblers" = "Plant and Machine Operators and Assemblers",
                      "Bus and tram drivers" = "Plant and Machine Operators and Assemblers",
                      "Food and related products machine operators" = "Plant and Machine Operators and Assemblers",
                      "Lifting truck operators" = "Plant and Machine Operators and Assemblers",
                      "Other machine operat not else class" = "Plant and Machine Operators and Assemblers",
                      "Motor vehicle drivers" = "Plant and Machine Operators and Assemblers",
                     "Woodworking machine setter,setter-operator"= "Plant and Machine Operators and Assemblers",
                      "Machine-tool operators" = "Plant and Machine Operators and Assemblers",
                     "Machine operators and assemblers"= "Plant and Machine Operators and Assemblers",
                      "Machinery mechanics and fitters" = "Plant and Machine Operators and Assemblers",
                      "Sewing-machine operators" = "Plant and Machine Operators and Assemblers",
                      "Motorised farm, forestry plant operator" = "Plant and Machine Operators and Assemblers",
                     "Shoe-makers and related workers"  = "Plant and Machine Operators and Assemblers",
                     "Bleaching,dyeing,cleaning-machine operat"  = "Plant and Machine Operators and Assemblers",
                     "Wood-products machine operators" = "Plant and Machine Operators and Assemblers",
                     "Weaving- and knitting-machine operators" = "Plant and Machine Operators and Assemblers",
                     "Meat, fishprocess machine operator" = "Plant and Machine Operators and Assemblers",
                     "Railway brakers, signallers and shunters" = "Plant and Machine Operators and Assemblers",
                      "Assemblers" = "Plant and Machine Operators and Assemblers",
                     "Glass,ceramics kiln,related machine operator" = "Plant and Machine Operators and Assemblers",
                      "Locomotive engine drivers" = "Plant and Machine Operators and Assemblers",
                     "Crane, hoist and related plant operators" = "Plant and Machine Operators and Assemblers",
                     "Ships' deck crews and related workers" = "Plant and Machine Operators and Assemblers",
                     "Wood-processing-plant operators" = "Plant and Machine Operators and Assemblers",
                     "Metal melters,casters,rolling-mill operator" = "Plant and Machine Operators and Assemblers",
                     "Earth-moving  and related plant operators" = "Plant and Machine Operators and Assemblers",
                     "Rubber-products machine operators"= "Plant and Machine Operators and Assemblers",
                     "Lifting-truck operators"= "Plant and Machine Operators and Assemblers",
                     "Plastic-products machine operators" = "Plant and Machine Operators and Assemblers",
                     "Baked g,cereal,chocolateprod machine operat" = "Plant and Machine Operators and Assemblers",
                     "Industrial robot operators" = "Plant and Machine Operators and Assemblers",    
                     "Metal finish, plating,coatingmachine operat"= "Plant and Machine Operators and Assemblers",
                     "Steam-engine and boiler operators" = "Plant and Machine Operators and Assemblers", 
                     "Papermaking-plant operators" = "Plant and Machine Operators and Assemblers", 
                     "Chemical-processing-plant operators" = "Plant and Machine Operators and Assemblers", 
                     "Electronic-equipment assemblers"= "Plant and Machine Operators and Assemblers",
                     "Employment agents and labour contractors"= "Plant and Machine Operators and Assemblers",
                     "Brewer,wine, other beverage machine operat" = "Plant and Machine Operators and Assemblers", 
                     "Fibreprep,spinning winding-machine operat" = "Plant and Machine Operators and Assemblers",
                     "Fruit,vegetable,nutprocess-machine operat" = "Plant and Machine Operators and Assemblers",
                     "Chemicalprocess,plant operat not else class"= "Plant and Machine Operators and Assemblers",
                     "Paperboard,textile, related prod assembl"= "Plant and Machine Operators and Assemblers",
                     "Chemicalprod, machine operat not else class" = "Plant and Machine Operators and Assemblers",
                     "Motorcycle drivers"= "Plant and Machine Operators and Assemblers",
                     "Ore and metal furnace operators" = "Plant and Machine Operators and Assemblers",
                     "Metal,rubber,plastic-prod assemblers"= "Plant and Machine Operators and Assemblers",
                     "Agricultural,other mobile plant operator" = "Plant and Machine Operators and Assemblers",
                     "Power-Prod. and related plant operators" = "Plant and Machine Operators and Assemblers",              
                     "Wood-processing, papermaking-plant operator" = "Plant and Machine Operators and Assemblers",  
                     "Dairy-products machine operators"= "Plant and Machine Operators and Assemblers",
                     "Dairy products workers" = "Plant and Machine Operators and Assemblers",
                     "Printing-machine operators" = "Plant and Machine Operators and Assemblers",
                     "Textile,fur,leatherprod machine operator"   = "Plant and Machine Operators and Assemblers",                      
                     "Textl,fur,leatherprod mach operat n else clas" = "Plant and Machine Operators and Assemblers",
                     "Metal,mineralproducts machine operator" = "Plant and Machine Operators and Assemblers",            
                     "Pharmaceutical,toiletry-prod machine operat"  = "Plant and Machine Operators and Assemblers",
                      "Cement, other mineral prod machine operator"  = "Plant and Machine Operators and Assemblers",  
                     "Electrical-equipment assemblers" = "Plant and Machine Operators and Assemblers",  
                      "Wood and related products assemblers"= "Plant and Machine Operators and Assemblers",
                      "Printing,binding,paperprod machine operat"= "Plant and Machine Operators and Assemblers",
                     "Glass, ceramics,related plant operators" = "Plant and Machine Operators and Assemblers",
                     "Plant and machine operators and assemblers"= "Plant and Machine Operators and Assemblers",
                     "Metal-heat-treating-plant operators" = "Plant and Machine Operators and Assemblers",
                     "Mineralore,stone-processing-plant operator"= "Plant and Machine Operators and Assemblers",
                     "Power-production plant operators"= "Plant and Machine Operators and Assemblers",
                     "Metal-processing plant operators"= "Plant and Machine Operators and Assemblers",
                     "Glass,ceramic,rel plant operat not else class"= "Plant and Machine Operators and Assemblers",
                     "Locomotive engine drivers,related worker"= "Plant and Machine Operators and Assemblers",
                     "Mining, mineral-processing-plant operator"= "Plant and Machine Operators and Assemblers",
                     "Paper-pulp plant operators" = "Plant and Machine Operators and Assemblers",
                     "Optical and electronic equipment operators"= "Plant and Machine Operators and Assemblers",
                     "Food,related products machine operator" = "Plant and Machine Operators and Assemblers",
                     "Chemical,filtering,separating-equip operator" = "Plant and Machine Operators and Assemblers",
                     "Tea, coffee, cocoaprocess-machine operat" = "Plant and Machine Operators and Assemblers",
                     "Drivers and mobile plant operators" = "Plant and Machine Operators and Assemblers",
                     "Sugar production machine operators" = "Plant and Machine Operators and Assemblers",
                     "Ammunition,explosive products machine operat"= "Plant and Machine Operators and Assemblers",
                     "Metal drawers and extruders"= "Plant and Machine Operators and Assemblers",
                     "Mining plant operators"= "Plant and Machine Operators and Assemblers",
                     "Tobacco production machine operators"= "Plant and Machine Operators and Assemblers",
                     "Grain- and spice-milling-machine operators"= "Plant and Machine Operators and Assemblers",
                     "Fur,leatherprep machine operat"= "Plant and Machine Operators and Assemblers",
                     "Crush,grind,chemicalmixing machinery operat"= "Plant and Machine Operators and Assemblers",
                     "Chemical-heat-treating-plant operators"= "Plant and Machine Operators and Assemblers",
                     "Petrol,natural gas refin plant operator"= "Plant and Machine Operators and Assemblers",
                     "Rubber,plasticproducts machine operator"= "Plant and Machine Operators and Assemblers",
                     "Paper-products machine operators"= "Plant and Machine Operators and Assemblers",
                     "Composite products assemblers"= "Plant and Machine Operators and Assemblers",
                     "Stationary plant and related operators"= "Plant and Machine Operators and Assemblers",
                     "Bookbinding-machine operators"= "Plant and Machine Operators and Assemblers",
                     "Shoemaking- and related machine operators"= "Plant and Machine Operators and Assemblers",
                     "Photographic and related workers"= "Plant and Machine Operators and Assemblers",
                     "Photographic-products machine operators"= "Plant and Machine Operators and Assemblers",
                     "Chemical-products machine operators"= "Plant and Machine Operators and Assemblers",
                     "Mechanical-machinery assemblers"= "Plant and Machine Operators and Assemblers",
                     "Well drillers,borers and related worker"= "Plant and Machine Operators and Assemblers",
                     "Chem-still,reactor opt,except petr, nat gas"= "Plant and Machine Operators and Assemblers",

                     
                      "Cleaners and helpers in offices, hotels and other establishments" = "Elementary Occupations",
                      "Kitchen helpers" = "Elementary Occupations",
                      "Domestic helpers and cleaners" ="Elementary Occupations",
                      "Freight handlers" = "Elementary Occupations",
                      "Manufacturing labourers not elsewhere classified" = "Elementary Occupations",
                      "Building caretakers" = "Elementary Occupations",
                     "Labourer mining,construction,manufact,transp"= "Elementary Occupations",
                      "Farm-hands and labourers" = "Elementary Occupations",
                      "Shelf fillers" = "Elementary Occupations",
                      "Crop farm labourers" = "Elementary Occupations",
                      "Building construction labourers" = "Elementary Occupations",
                      "Hand packers" = "Elementary Occupations", 
                      "Manufacturing labourers"= "Elementary Occupations",
                      "Shop,stall,market salespers, demonstrators" = "Services and Sales Workers",
                      "Helper,cleaner in office,hotel,other establ" = "Elementary Occupations",
                      "Transport laborers and freight handlers" = "Elementary Occupations", 
                      "Doorkeepers,watchpersons,related worker" = "Elementary Occupations",
                      "Domestic,related helpers,cleaner,launderer" = "Elementary Occupations",
                      "Constr,mainten labour: roads,dams,sim constr"  = "Elementary Occupations", 
                      "Messengers,package,luggage porter, deliverer"  = "Elementary Occupations", 
                      "Agricultural,fishery,related labourers"  = "Elementary Occupations", 
                     "Street vendors"  = "Elementary Occupations",
                      "Hand-launderers and pressers"  = "Elementary Occupations",
                     "Forestry labourers" = "Elementary Occupations",
                     "Garbage collectors" = "Elementary Occupations",
                     "Elementary occupations"= "Elementary Occupations",
                     "Garbage collectors and related labourers" = "Elementary Occupations",
                     "Mining and construction labourers" = "Elementary Occupations",
                     "Mining and quarrying labourers" = "Elementary Occupations",
                     "Vehicle, window and related cleaners"= "Elementary Occupations",
                     "Miners and quarry workers"= "Elementary Occupations",
                     "Messengers,porters doorkeepers,rel worker"= "Elementary Occupations",
                     "Sales and services elementary occupations" = "Elementary Occupations",
                     "Street vendors and related workers" = "Elementary Occupations",
                     "Sweepers and related labourers" = "Elementary Occupations",
                     "Fishery, hunting and trapping labourers" = "Elementary Occupations",
                     "Shoe cleaning,other streetserv element occ" = "Elementary Occupations",
                     "Vendingm,money collect, meter reader,rel work"= "Elementary Occupations",
                      
                      "Armed forces" = "Armed Forces", 
                     
                     
  ))





summary(ESS02$OCCUPATION)

ESS02$OCCUPATION <- factor(ESS02$OCCUPATION, ordered = TRUE)

names(ESS02)
ESS02 <- rename(
  ESS02,
  HOMOSEX_gen = freehms,
  SALIENCE_rel = rlgdgr,
  ATTENDANCE_rel = rlgatnd,
  PRAY_rel = pray,
  BELONG_rel = rlgblg,
  DENOMINATION_rel = rlgdnm,
  AGE = AGE6cat,
  MARITAL_STATUS =  marital,
  INCOME = hinctnt,
  POSTMAT_env = impenv,
  CHILDREN = chldhhe,
  IMMIGRANT_att_country = imwbcnt,
  IMMIGRANT_att_culture = imueclt,
  TRAD_GEND = mnrgtjb
  
)
names(ESS02)

ESS02<- select(ESS02, essround, cntry, HOMOSEX_gen, gndr, SALIENCE_rel,
               ATTENDANCE_rel, PRAY_rel, BELONG_rel, DENOMINATION_rel, agea, AGE, MARITAL_STATUS, EDUCATION, INCOME,
               domicil, POSTMAT_env, CHILDREN, IMMIGRANT_att_country, IMMIGRANT_att_culture, OCCUPATION, TRAD_GEND, dweight,
               pspwght, pweight)

summary(ESS02)



library(rio)
export(ESS02, "ESS02 Recoded.dta")
