rm(list = ls())

#packages we need for data management 
library(foreign)
library(dplyr)

#setting WD and loading data 
setwd("C:/Users/giann/Desktop/DAPS/Multivariate analysis/RESEARCH PROJECT/dataset/ESS/ESS8/ESS8e02_1.stata")
ESS8 <- read.dta("ESS8e02_1.dta")

View(ESS8$isco08)

#selecting the needed variables 
ESS8_00 <- select(ESS8, essround, cntry, freehms, hmsfmlsh, hmsacld, gndr, rlgdgr,
                  rlgatnd, pray, rlgblg, rlgdnm, agea, marsts, edulvlb, hinctnta,
                  domicil, impenv, chldhhe,imwbcnt, imueclt, isco08, mnrgtjb, dweight,
                  pspwght, pweight)

summary(ESS8_00)

#cntry var: transformed as factor (categorical)
ESS8_00$cntry<- as.factor(ESS8_00$cntry)
summary(ESS8_00$cntry)

#selecting countries: we have 16 countries in common in the three dataset 
ESS8_00 <- filter(
  ESS8_00,
  cntry %in% c("AT", "BE", "CH", "CZ", "DE", "EE", "FI", "FR", "GB", "HU", "IE", "IT", "NO", "PL", "NL", "SI")
)

#recoding variable age in six categories 
ESS8_00$AGE6cat <- ifelse(ESS8_00$agea < 25,
                      "15-24",
                      ifelse(ESS8_00$agea < 35,
                             "25-34",
                             ifelse(ESS8_00$agea < 45,
                                    "35-44",
                                    ifelse(ESS8_00$agea < 55,
                                           "45-54",
                                           ifelse(ESS8_00$agea < 65,
                                                  "55-64",
                                                  ifelse(ESS8_00$agea < 75,
                                                         "65-74",
                                                          "75+"))))
                             
                      )
)

ESS8_00$AGE6cat <- factor(ESS8_00$AGE6cat, ordered = TRUE)

summary(ESS8_00)
summary(ESS8_00$AGE6cat)

#recode level of education
summary(ESS8_00$edulvlb)

ESS8_00 <- mutate(
  ESS8_00,
  EDUCATION = recode(edulvlb,
                   "Not completed ISCED level 1" = "Low level",
                   "ISCED 1, completed primary education" = "Low level",
                   "Vocational ISCED 2C < 2 years, no access ISCED 3" = "Low level",
                   "General/pre-vocational ISCED 2A/2B, access ISCED 3 vocational" = "Low level",
                   "General ISCED 2A, access ISCED 3A general/all 3" = "Low level",
                   "Vocational ISCED 2C >= 2 years, no access ISCED 3" = "Low level",
                   "Vocational ISCED 2A/2B, access ISCED 3 vocational"  = "Low level",
                   "Vocational ISCED 2, access ISCED 3 general/all"= "Low level",
                   "Vocational ISCED 3C < 2 years, no access ISCED 5"= "Medium level",
                   "General ISCED 3 >=2 years, no access ISCED 5"= "Medium level",
                   "General ISCED 3A/3B, access ISCED 5B/lower tier 5A"= "Medium level",
                   "General ISCED 3A, access upper tier ISCED 5A/all 5"= "Medium level",
                   "Vocational ISCED 3C >= 2 years, no access ISCED 5"= "Medium level",
                   "Vocational ISCED 3A, access ISCED 5B/ lower tier 5A"= "Medium level",
                   "Vocational ISCED 3A, access upper tier ISCED 5A/all 5"= "Medium level",
                   "General ISCED 4A/4B, access ISCED 5B/lower tier 5A" = "Medium level",
                   "General ISCED 4A, access upper tier ISCED 5A/all 5" = "Medium level",
                   "ISCED 4 programmes without access ISCED 5" = "Medium level",
                   "Vocational ISCED 4A/4B, access ISCED 5B/lower tier 5A" = "Medium level",
                   "Vocational ISCED 4A, access upper tier ISCED 5A/all 5" = "Medium level",
                   "ISCED 5A short, intermediate/academic/general tertiary below bachelor" = "High level",
                   "ISCED 5B short, advanced vocational qualifications" = "High level",
                   "ISCED 5A medium, bachelor/equivalent from lower tier tertiary" = "High level",
                   "ISCED 5A medium, bachelor/equivalent from upper/single tier tertiary" = "High level",
                   "ISCED 5A long, master/equivalent from lower tier tertiary" = "High level",
                   "ISCED 5A long, master/equivalent from upper/single tier tertiary" = "High level",
                   "ISCED 6, doctoral degree" = "High level"))
                   
summary(ESS8_00$EDUCATION)
  
ESS8_00$EDUCATION <- factor(ESS8_00$EDUCATION, ordered = TRUE)

summary(ESS8_00$EDUCATION)     #look what is changed 
summary(ESS8_00)

#recode occupations
View(ESS8_00$isco08)


ESS8_00 <- mutate(
  ESS8_00,
  OCCUPATION = recode(isco08,
                      "Managing directors and chief executives" = "Managers",
                      "Manufacturing managers" = "Managers",
                      "Retail and wholesale trade managers" = "Managers",
                      "Sales and marketing managers" = "Managers",
                      "Supply, distribution and related managers" = "Managers",
                      "Restaurant managers" = "Managers",
                      "Construction managers" = "Managers",
                      "Education managers" = "Managers",
                      "Professional services managers not elsewhere classified" = "Managers",
                      "Services managers not elsewhere classified" = "Managers",
                      "Secondary education teachers" = "Professionals",
                      "Nursing associate professionals" = "Professionals",
                      "Primary school teachers" = "Professionals",
                      "Nursing professionals" = "Professionals",
                      "Accountants" = "Professionals",
                      "Social work and counselling professionals" = "Professionals",
                      "Early childhood educators" = "Professionals",
                      "Teaching professionals" = "Professionals",
                      "Teaching professionals not elsewhere classified" = "Professionals",
                      "University and higher education teachers" = "Professionals",
                      "Management and organization analysts" = "Professionals",
                      "Software developers" = "Professionals",
                      "Policy administration professionals" = "Professionals",
                      "Vocational education teachers" = "Professionals",
                      "Technical and medical sales professionals (excluding ICT)" = "Professionals",
                      "Civil engineers" = "Professionals",
                      "Lawyers" = "Professionals",
                      "Advertising and marketing professionals" = "Professionals",
                      "Engineering professionals not elsewhere classified" = "Professionals",
                      "Mechanical engineers" = "Professionals",
                      "Financial and investment advisers" = "Professionals",
                      "Accounting associate professionals" = "Technicians and Associate Professionals",
                      "Social work associate professionals" = "Technicians and Associate Professionals",
                      "Administrative and executive secretaries" = "Technicians and Associate Professionals",
                      "Commercial sales representatives" = "Technicians and Associate Professionals",
                      "Manufacturing supervisors" = "Technicians and Associate Professionals",
                      "Office supervisors" = "Technicians and Associate Professionals",
                      "Insurance representatives" = "Technicians and Associate Professionals",
                      "Buyers" = "Technicians and Associate Professionals",
                      "Physical and engineering science technicians not elsewhere classified" = "Technicians and Associate Professionals",
                      "General office clerks " = "Clerical Support Workers",
                      "Accounting and bookkeeping clerks" = "Clerical Support Workers",
                      "Secretaries (general)" = "Clerical Support Workers",
                      "Stock clerks" = "Clerical Support Workers",
                      "Mail carriers and sorting clerks" = "Clerical Support Workers",
                      "Bank tellers and related clerks" = "Clerical Support Workers",
                      "Receptionists (general)" = "Clerical Support Workers",
                      "Transport clerks" = "Clerical Support Workers",
                      "Shop sales assistants" = "Services and Sales Workers",
                      "Waiters" = "Services and Sales Workers",
                      "Cooks" = "Services and Sales Workers",
                      "Health care assistants" = "Services and Sales Workers",
                      "Child care workers" = "Services and Sales Workers",
                      "Home-based personal care workers" = "Services and Sales Workers",
                      "Hairdressers" = "Services and Sales Workers",
                      "Cashiers and ticket clerks" = "Services and Sales Workers",
                      "Shop keepers" = "Services and Sales Workers",
                      "Security guards" = "Services and Sales Workers",
                      "Shop supervisors" = "Services and Sales Workers",
                      "Teachers' aides" = "Services and Sales Workers",
                      "Beauticians and related workers" = "Services and Sales Workers",
                      "Police officers" = "Services and Sales Workers",
                      "Bartenders" = "Services and Sales Workers",
                      "Mixed crop and animal producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Livestock and dairy producers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Gardeners, horticultural and nursery growers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Motor vehicle mechanics and repairers" = "Craft and Related Trades Workers",
                      "Carpenters and joiners" = "Craft and Related Trades Workers",
                      "Bricklayers and related workers" = "Craft and Related Trades Workers",
                      "Building and related electricians" = "Craft and Related Trades Workers",
                      "Metal working machine tool setters and operators" = "Craft and Related Trades Workers",
                      "Agricultural and industrial machinery mechanics and repairers" = "Craft and Related Trades Workers",
                      "Plumbers and pipe fitters" = "Craft and Related Trades Workers",
                      "Tailors, dressmakers, furriers and hatters" = "Craft and Related Trades Workers",
                      "Bakers, pastry-cooks and confectionery makers" = "Craft and Related Trades Workers",
                      "Structural-metal preparers and erectors" = "Craft and Related Trades Workers",
                      "Painters and related workers" = "Craft and Related Trades Workers",
                      "House builders" = "Craft and Related Trades Workers",
                      "Welders and flamecutters" = "Craft and Related Trades Workers",
                      "Electrical mechanics and fitters" = "Craft and Related Trades Workers",
                      "Cabinet-makers and related workers" = "Craft and Related Trades Workers",
                      "Product graders and testers (excluding foods and beverages)" = "Craft and Related Trades Workers",
                      "Heavy truck and lorry drivers" = "Plant and Machine Operators and Assemblers",
                      "Car, taxi and van drivers" = "Plant and Machine Operators and Assemblers",
                      "Mechanical machinery assemblers" = "Plant and Machine Operators and Assemblers", 
                      "Bus and tram drivers" = "Plant and Machine Operators and Assemblers",
                      "Food and related products machine operators" = "Plant and Machine Operators and Assemblers",
                      "Lifting truck operators" = "Plant and Machine Operators and Assemblers",
                      "Cleaners and helpers in offices, hotels and other establishments" = "Elementary Occupations",
                      "Kitchen helpers" = "Elementary Occupations",
                      "Domestic cleaners and helpers" = "Elementary Occupations",
                      "Freight handlers" = "Elementary Occupations",
                      "Manufacturing labourers not elsewhere classified" = "Elementary Occupations",
                      "Building caretakers" = "Elementary Occupations",
                      "Shelf fillers" = "Elementary Occupations",
                      "Crop farm labourers" = "Elementary Occupations",
                      "Building construction labourers" = "Elementary Occupations",
                      "Hand packers" = "Elementary Occupations",
                      "Construction supervisors" = "Technicians and Associate Professionals",
                      "General office clerks" = "Clerical Support Workers",
                      "Sewing machine operators" = "Pland and Machine Operators and Assemblers",
                      "Clerical support workers not elsewhere classified" = "Clerical Support Workers",
                      "Finance managers" = "Managers",
                      "Elementary workers not elsewhere classified" = "Elementary occupations",
                      "Information and communications technology service managers" = "Managers",
                      "Specialist medical practitioner" = "Professionals",
                      "Messengers, package deliverers and luggage porters" = "Elementary occupations",
                      "Field crop and vegetable grower" = "Skilled Agricultural, Foresty and Fishery Workers",
                      "Business services and administration managers not elsewhere classified" = "Managers",
                      "Business services and administration managers not elsewhere classified" = "Managers",
                      "Human resource managers" = "Managers",
                      "Civil engineering technicians" = "Technicians and Associate Professionals",
                      "Generalist medical practitioners" = "Professionals",
                      "Personal care workers in health services not elsewhere classified" = "Services and Sales Workers", 
                      "Police inspectors and detectives" = "Technicians and Associate Professionals",
                      "Real estate agents and property managers" = "Technicians and Associate Professionals",
                      "Systems analysts" = "Professionals",
                      "Building architects" = "Professionals",
                      "Personnel and careers professionals" = "Professionals" , 
                      "Training and staff development professionals" = "Professionals",
                      "Earthmoving and related plant operators" = "Plant and Machine Operators and Assemblers" ,
                      "Manufacturing labourers" = "Elementary Occupations",
                      "Mechanical engineering technicians" = "Technicians and Associate Professionals", 
                      "Domestic, hotel and office cleaners and helpers" = "Elementary Occupations",
                      "Policy and planning managers" = "Managers", 
                      "Statistical, finance and insurance clerks" = "Clerical Support Workers",
                      "Toolmakers and related workers" = "Craft and Related Trades Workers",
                      "Journalists" = "Professionals",
                      "Metal processing plant operators" = "Plant and Machine Operators and Assemblers",
                      "Assemblers not elsewhere classified" = "Plant and Machine Operators and Assemblers",
                      "Chefs" = "Elementary Occupations",
                      "Medical secretaries" = "Technicians and Associate Professionals",
                      "Food service counter attendants" = "Services and Sales Workers",
                      "Butchers, fishmongers and related food preparers" = "Craft and Related Trades Workers",
                      "Science and engineering professionals" = "Professionals",
                      "Government social benefits officials" = "Technicians and Associate Professionals",
                      "Financial and insurance services branch managers" = "Managers",
                      "Draughtspersons" = "Technicians and Associate Professionals", 
                      "Mobile farm and forestry plant operators" = "Plant and Machine Operators and Assemblers",
                      "Crane, hoist and related plant operators" = "Plant and Machine Operators and Assemblers",
                      "Industrial and production engineers" = "Professionals",
                      "Special needs teachers" = "Professionals",
                      "Regulatory government associate professionals not elsewhere classified" = "Technicians and Associate Professionals",
                      "Sewing, embroidery and related workers" = "Craft and Related Trades Workers",
                      "Civil engineering labourers" = "Elementary Occupations",
                      "Information and communications technology user support technicians" = "Technicians and Associate Professionals",
                      "Stationary plant and machine operators not elsewhere classified" = "Plant and Machine Operators and Assemblers",
                      "Contact centre information clerks" = "Clerical Support Workers",
                      "Stationary plant and machine operators" = "Plant and Machine Operators and Assemblers",
                      "Software and applications developers and analysts not elsewhere classified" = "Professionals",
                      "Legal professionals not elsewhere classified" = "Professionals",
                      "Clerical support workers" = "Clerical Support Workers",
                      "Sweepers and related labourers" = "Elementary Occupations",
                      "Medical and pathology laboratory technicians" = "Technicians and Associate Professionals",
                      "Other clerical support workers" = "Clerical Support Workers",
                      "Forestry and related workers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Garden and horticultural labourer" = "Elementary Occupations",	
                      "Business services and administration managers" = "Managers",
                      "Pharmaceutical technicians and assistants" = "Technicians and Associate Professionals",
                      "Government tax and excise officials" = "Technicians and Associate Professionals",
                      "Building frame and related trades workers not elsewhere classified" = "Craft and Related Trades Workers",
                      "Government licensing officials" = "Technicians and Associate Professionals",
                      "Computer network and systems technicians" = "Technicians and Associate Professionals",
                      "Telephone switchboard operators" = "Clerical Support Workers",
                      "Sports coaches, instructors and officials" = "Technicians and Associate Professionals",
                      "Electrical and electronic equipment assemblers" = "Plant and Machine Operators and Assemblers",
                      "Armed forces occupations" = "Armed Forces Occupations",
                      "Armed forces occupations, other ranks" = "Armed Forces Occupations",
                      "Psychologists" = "Professionals",
                      "Business and administration associate professionals" = "Technicians and Associate Professionals",
                      "Drivers and mobile plant operators" = "Plant and Machine Operators and Assemblers",
                      "Fitness and recreation instructors and program leaders" = "Technicians and Associate Professionals",
                      "Production clerks" = "Clerical Support Workers",
                      "Cleaning and housekeeping supervisors in offices, hotels and other establishment" = "Services and Sales Workers",
                      "Packing, bottling and labelling machine operators" = "Plant and Machine Operators and Assemblers",
                      "Hotel managers" = "Managers",
                      "Pharmacists" = "Professionals",
                      "Wood processing plant operators" = "Plant and Machine Operators and Assemblers",
                      "Financial analysts" = "Professionals",
                      "Science and engineering associate professionals" = "Technicians and Associate Professionals",
                      "Legal, social, cultural and related associate professionals" = "Professionals",
                      "Payroll clerks" = "Clerical Support Workers",
                      "Spray painters and varnishers" = "Craft and Related Trades Workers",
                      "Printers" = "Craft and Related Trades Workers",
                      "Legal, social and cultural professionals" = "Professionals", 
                      "Chemical and physical science technicians" = "Technicians and Associate Professionals",
                      "Credit and loans officers" = "Technicians and Associate Professionals",
                      "Personnel clerks" =  "Clerical Support Workers",
                      "Mixed crop and livestock farm labourers" = "Elementary Occupations",
                      "Pland and Machine Operators and Assemblers" = "Plant and Machine Operators and Assemblers",
                      "Specialist medical practitioners" = "Professionals",
                      "Field crop and vegetable growers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Health services managers" = "Managers",
                      "Graphic and multimedia designers" = "Professionals",
                      "Musicians, singers and composers" = "Professionals",
                      "Photographers" = "Technicians and Associate Professionals",
                      "Personal care workers in health services" = "Services and Sales Workers",
                      "Roofers" = "Craft and Related Trades Workers",
                      "Plastic products machine operators" = "Plant and Machine Operators and Assemblers",
                      "Physiotherapy technicians and assistants" = "Technicians and Associate Professionals",
                      "Armed forces occupations" = "Armed Forces Occupations",
                      "Physiotherapists" = "Professionals",
                      "Chemical products plant and machine operators" = "Plant and Machine Operators and Assemblers",
                      "Mining and quarrying labourers" = "Elementary Occupations",
                      "Electrical engineers" = "Professionals",
                      "Translators, interpreters and other linguists" = "Professionals",
                      "Medical assistants" = "Technicians and Associate Professionals",
                      "Enquiry clerks" = "Clerical Support Workers",
                      "Personal service workers" = "Services and Sales Workers",
                      "Electrical line installers and repairers" = "Craft and Related Trades Workers",
                      "Electrical engineering technicians" = "Technicians and Associate Professionals",
                      "Sheet-metal workers" = "Craft and Related Trades Workers",
                      "Railway brake, signal and switch operators" = "Plant and Machine Operators and Assemblers",
                      "Commissioned armed forces officers" = "Armed Forces Occupations",
                      "Research and development managers" = "Managers",
                      "Dental assistants and therapists" = "Technicians and Associate Professionals",
                      "Hotel receptionists" = "Clerical Support Workers",
                      "Floor layers and tile setters" =  "Craft and Related Trades Workers",
                      "Locomotive engine drivers" = "Plant and Machine Operators and Assemblers",
                      "Legal secretaries" = "Technicians and Associate Professionals",
                      "Client information workers not elsewhere classified" = "Clerical Support Workers",
                      "Fire-fighters" = "Services and Sales Workers", 
                      "Systems administrators" = "Professionals",
                      "Film, stage and related directors and producers" = "Professionals",
                      "Mining and metallurgical technicians" = "Technicians and Associate Professionals",
                      "Electronics mechanics and servicers" =  "Craft and Related Trades Workers",
                      "Metal finishing, plating and coating machine operators" = "Plant and Machine Operators and Assemblers",
                      "Odd job persons" = "Elementary Occupations",
                      "Metal, machinery and related trades workers" = "Craft and Related Trades Workers",
                      "Administrative and commercial managers" = "Managers",
                      "Farming, forestry and fisheries advisers" = "Professionals",
                      "Electronics engineering technicians" = "Technicians and Associate Professionals",
                      "Concrete placers, concrete finishers and related workers" = "Craft and Related Trades Workers",
                      "Plasterers" =  "Craft and Related Trades Workers",
                      "Information and communications technology installers and servicers" = "Craft and Related Trades Workers",
                      "Sports, recreation and cultural centre managers" = "Managers",
                      "Electronics engineers" = "Professionals",
                      "Information and communications technology operations and user support technician" = "Technicians and Associate Professionals",
                      "Information and communications technology operations technicians" =  "Technicians and Associate Professionals",
                      "Contact centre salespersons" = "Services and Sales Workers",
                      "Jewellery and precious-metal workers" = "Craft and Related Trades Workers",
                      "Miners and quarriers" = "Plant and Machine Operators and Assemblers",
                      "Hotel and restaurant managers" = "Managers",
                      "Librarians and related information professionals" = "Professionals",
                      "Mining, manufacturing and construction supervisors" = "Technicians and Associate Professionals",
                      "Senior government officials" = "Managers",
                      "Telecommunications engineers" = "Professionals",
                      "Information and communications technology sales professionals" = "Professionals",
                      "Typists and word processing operators" = "Clerical Support Workers",
                      "Domestic housekeepers" = "Services and Sales Workers",
                      "Livestock farm labourers" = "Elementary Occupations",
                      "Garbage and recycling collectors" = "Elementary Occupations",
                      "Health professionals not elsewhere classified" = "Professionals",
                      "Applications programmers" = "Professionals",
                      "Trade brokers" = "Technicians and Associate Professionals",
                      "Data entry clerks" = "Clerical Support Workers",
                      "Shop salespersons" = "Services and Sales Workers",
                      "Building finishers and related trades workers" = "Craft and Related Trades Workers",
                      "Production and specialised services managers" = "Managers",
                      "Other teaching professionals" = "Professionals",
                      "Business and administration professionals" = "Professionals",
                      "Elementary occupations" = "Elementary occupations",
                      "Pland and Machine Operators and Assemblers" = "Pland and Machine Operators and Assemblers",
                      "Armed Forces Occupations" = "Armed Forces Occupations",
                      "Garden and horticultural labourers" = "Elementary occupations",
                      "Sales and purchasing agents and brokers" = "Technicians and Associate Professionals",
                      "Employment agents and contractors" = "Technicians and Associate Professionals",
                      "Administrative and specialised secretaries" = "Technicians and Associate Professionals",
                      "Travel consultants and clerks" = "Clerical Support Workers",
                      "Craft and related workers not elsewhere classified" = "Craft and Related Trades Workers",
                      "Laundry machine operators" = "Plant and Machine Operators and Assemblers",
                      "Aged care services managers" = "Managers",
                      "Dentists" = "Professionals",
                      "Traditional and complementary medicine associate professionals"= "Technicians and Associate Professionals",
                      "Transport conductors" = "Services and Sales Workers",
                      "Pet groomers and animal care workers" = "Services and Sales Workers",
                      "Biologists, botanists, zoologists and related professionals" = "Professionals",
                      "Other language teachers" = "Professionals",
                      "Economists" = "Professionals",
                      "Ships' deck officers and pilots" = "Technicians and Associate Professionals",
                      "Dispensing opticians" =  "Technicians and Associate Professionals",
                      "Stall and market salespersons" = "Services and Sales Workers",
                      "Service station attendants" = "Services and Sales Workers",
                      "Craft and related trades workers" = "Craft and Related Trades Workers", 
                      "Building and related trades workers, excluding electricians" = "Craft and Related Trades Workers", 
                      "Food and beverage tasters and graders" = "Craft and Related Trades Workers",
                      "Chemists" = "Professionals",
                      "Cartographers and surveyors" = "Professionals",
                      "Paramedical practitioners" = "Professionals",
                      "Education methods specialists" = "Professionals",
                      "Other arts teachers" = "Professionals",
                      "Health associate professionals not elsewhere classified" = "Technicians and Associate Professionals",
                      "Other artistic and cultural associate professionals" = "Technicians and Associate Professionals",
                      "Library clerks" = "Clerical Support Workers",
                      "Food processing, wood working, garment and other craft and related trades worker" = "Craft and Related Trades Workers",
                      "Weaving and knitting machine operators" = "Plant and Machine Operators and Assemblers",
                      "Other cleaning workers" = "Elementary Occupations",
                      "Agricultural and forestry production managers" = "Managers",
                      "Product and garment designers" = "Professionals",
                      "Other music teachers" = "Professionals",
                      "Process control technicians not elsewhere classified" = "Technicians and Associate Professionals",
                      "Securities and finance dealers and brokers" = "Technicians and Associate Professionals",
                      "Conference and event planners" = "Technicians and Associate Professionals",
                      "Driving instructors" = "Services and Sales Workers",
                      "Mixed crop growers" = "Skilled Agricultural, Forestry and Fishery Workers",
                      "Heavy truck and bus drivers" = "Plant and Machine Operators and Assemblers",
                      "Cleaners and helpers" = "Elementary Occupations",
                      "Mining and construction labourers" = "Elementary Occupations",
                      "Child care services managers" = "Managers",
                      "Architects, planners, surveyors and designers" = "Professionals",
                      "Public relations professionals" = "Professionals",
                      
                    
  ))

summary(ESS8_00$OCCUPATION)
ESS8_00$OCCUPATION<- as.factor(ESS8_00$OCCUPATION)


#saving dataset
library(rio) 
export(ESS8_00, "ESS8_00Recoded.dta")



